### ISSUE TITLE
Unable to get media object serverside

### ISSUE THREAD

**Issue by DevShinx** [wyozi/gmod-medialib#28]
I would like to be able to get the metadata of a video serverside but I am unable to because of an error that occurs.

lua/autorun/medialib.lua:25: attempt to index global 'vgui' (a nil value)
1. get - lua/autorun/medialib.lua:25
   1. ctor - lua/autorun/medialib.lua:25
   2. unknown - lua/autorun/medialib.lua:5
      1. load - lua/autorun/medialib.lua:25
      2. unknown - RunString:12
      3. RunString - [C]:-1
      4. func - lua/autorun/luapad.lua:120
         1. unknown - lua/includes/modules/net.lua:32

**Comment by wyozi** [comment]
Serverside you should query the service.

``` lua
local service = medialib.load("media").guessService(link)
service:query(link, function(err, data)
    print(string.format("%s [%d]", data.title or "unknown", data.duration or -1))
end)
```

**Comment by DevShinx** [comment]
Oh, hey. I'm just dumb. Thanks for the help xD
