### ISSUE TITLE
Should 'ended' event be called on media stop?

### ISSUE THREAD

**Issue by wyozi** [wyozi/gmod-medialib#49]
Technically the media ends but unnaturally stopping the media might cause problems in code that uses events. 

Ex https://github.com/wyozi/wmc-plus/pull/4

**Comment by yupi2** [comment]
It might be useful so it could stay, but it probably shouldn't be used for playing the next song like in wmc-plus. It would be easiest to not change anything though and just keep it how it is. For wmcp-plus, maybe add a variable (something like wmcp.ShouldStop) that is checked in the event function to see if it shouldn't play the next song.

**Comment by wyozi** [comment]
I feel like having the ended event pass a parameter indicating whether the stop was due to calling stop() or the media ending naturally would be the optimal way. I don't see any other way to do a media change on media end in wmcp and such,
