### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aStonePenguin** [wyozi/gmod-medialib#61]
When using the example.

[HTML] Uncaught ReferenceError: medialibDelegate is not defined

**Comment by rafraser** [comment]
Happening to me as well.

**Comment by wyozi** [comment]
Seems to work fine in browser. I'll take a closer look ingame later.

**Comment by wyozi** [comment]
For some reason the https website on github that medialib uses for youtube does not load at all ingame, but the http version seems to work fine.

I'll push an update to change that.
