### ISSUE TITLE
Error on Load

### ISSUE THREAD

**Issue by JarosLucky** [wyozi/gmod-medialib#62]
[MediaLib] Loading unreferenced module mediabase
[MediaLib] Loading unreferenced module oop
[MediaLib] Creating module oop
[MediaLib] Registering oopclass Media
[MediaLib] Loading unreferenced module media
[MediaLib] Creating module media
[MediaLib] Loading unreferenced module serviceloader
[MediaLib] Loading unreferenced module servicebase
[MediaLib] Loading unreferenced module mediaregistry
[MediaLib] Creating module mediaregistry
[MediaLib] Registering oopclass Service
[MediaLib] Loading unreferenced module service_html
[MediaLib] Loading unreferenced module timekeeper
[MediaLib] Registering oopclass TimeKeeper
[MediaLib] Registering oopclass HTMLService
[MediaLib] Registering oopclass HTMLMedia
[MediaLib] Loading unreferenced module service_bass
[MediaLib] Registering oopclass BASSService
[MediaLib] Registering oopclass BASSMedia
[MediaLib] Registering service gdrive.lua
[MediaLib] Registering oopclass GDriveService
[MediaLib] Registering service mp4.lua
[MediaLib] Registering oopclass Mp4Service
[MediaLib] Registering service soundcloud.lua
[MediaLib] Registering oopclass SoundcloudService
[MediaLib] Registering service twitch.lua
[MediaLib] Registering oopclass TwitchService

[ERROR] lua/medialib/serviceloader.lua:16: attempt to index local 'err' (a nil value)
  1. unknown - lua/medialib/serviceloader.lua:16
   2. include - [C]:-1
    3. tryInclude - gamemodes/darkrp/gamemode/util/medialib.lua:47
     4. load - gamemodes/darkrp/gamemode/util/medialib.lua:67
      5. unknown - gamemodes/darkrp/gamemode/util/medialib_loader.lua:7
       6. include_cl - [C]:-1
        7. include_sh - gamemodes/darkrp/gamemode/sh_init.lua:24
         8. unknown - gamemodes/darkrp/gamemode/sh_init.lua:101
          9. include - [C]:-1
           10. unknown - gamemodes/darkrp/gamemode/cl_init.lua:1

**Comment by wyozi** [comment]
You should use the minified build at dist/medialib.lua

**Comment by JarosLucky** [comment]
hmm. okay, try.

**Comment by JarosLucky** [comment]
Thanks
