### ISSUE TITLE
Hello, I am Need help

### ISSUE THREAD

**Issue by kinj14** [wyozi/gmod-medialib#63]
Hello I'm looking to make an FFT system but I can not find an example or others, Thanks in advance

**Comment by wyozi** [comment]
https://github.com/wyozi/gmod-medialib/blob/master/ext/beatdetector.lua

https://github.com/wyozi/gmod-medialib/blob/master/examples/beatdetection.lua

**Comment by kinj14** [comment]
Hello, the problem is that I can not make it work for the FFT but your example works but not for fft

**Comment by wyozi** [comment]
Are you trying to use FFT with youtube? It only works with soundcloud or direct mp3.

**Comment by kinj14** [comment]
Ah okay pity :'(
