### ISSUE TITLE
Soundcloud BASS Detector dont work

### ISSUE THREAD

**Issue by ghost** [wyozi/gmod-medialib#65]
Hey im using the wyozi DJ Kit, the chromium branch make yt working but if i use soundcloud for the Lightningstreaks for the bass it dont work anymore.

[MediaLib] BassMedia play failed: BASS_ERROR_FILEOPEN

Maybe the chromium branch changed something idk.

**Comment by wyozi** [comment]
Thanks for the report. I'll try investigating this further later. Presumably the 64bit build breaks something in BASS.

**Comment by wyozi** [comment]
I tested a random soundcloud link in chromium branch and seems to work fine. Try again and see if it works now.

**Comment by ghost** [comment]
ok newest server/branch update fixed it now. thank you anyway.
