### ISSUE TITLE
YT API

### ISSUE THREAD

**Issue by ghost** [wyozi/gmod-medialib#68]
Hey im messaging you because the Wyozi DJ Kit with the change to the chromium beta branch is working for soundcloud.
I added my own YT API Key but when i request a YT Song it dont appears on the entity and dont get played.. there is a error 

DLL_MessageEnd: Refusing to send user message TextMsg of 256 bytes to client, user message size limit is 255 bytes

**Comment by wyozi** [comment]
Sounds really weird, since that's an usermessage error and DJ kit should use net messages. Probably related to some other Lua code on your server.

In any case, not a relevant bug report to this repo.

**Comment by Aws0mee** [comment]
I get this exact message too only when using this @LPDaVinci were you able to fix it?
