### ISSUE TITLE
Why is there self.events = {}

### ISSUE THREAD

**Issue by Pdzly** [wyozi/gmod-medialib#71]
https://github.com/wyozi/gmod-medialib/blob/962012a6ecc981eeef20833c2aa4b63fc7a71419/lua/medialib/servicebase.lua#L6-L10

The question is why is it there? Because it will just delete old events XD

**Comment by wyozi** [comment]
Ah, very good find. It definitely shouldn't be like that. I guess I never managed to test it with more than one event, ha
