### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Pyro-SeshRP** [wyozi/gmod-medialib#74]
I've been searching forever for another addon that beats wyozi's but hes made the best OG addons and i really want this and the DJ kit but installing them is impossible for me. I have no idea how to even start doing it

**Comment by Pyro-SeshRP** [comment]
Please pleassssse some help would be amazing

**Comment by wyozi** [comment]
Unrelated to this repo. Medialib is a library for media playback and can't be used as is
